# Notes on NumPy

### Import numpy

In [1]:
import numpy as np

### Create a 1-dimensional NumPy array using np.array()

In [2]:
oneD = np.array([1, 2, 3])
oneD

array([1, 2, 3])

### Create a 2-dimensional NumPy array using np.array()

In [4]:
twoD = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
twoD

array([[1, 2, 3],
       [4, 5, 6]])

### Create a 3-dimensional NumPy array using np.array()

In [5]:
threeD = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
threeD

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Attributes of 1-dimensional array
##### (shape, number of dimensions, data type, size and type)

In [7]:
oneD.shape, oneD.ndim, oneD.dtype, oneD.size, type(oneD)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

### Attributes of 2-dimensional array
##### (shape, number of dimensions, data type, size and type)

In [8]:
twoD.shape, twoD.ndim, twoD.dtype, twoD.size, type(twoD)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

### Attributes of 3-dimensional array
##### (shape, number of dimensions, data type, size and type)

In [9]:
threeD.shape, threeD.ndim, threeD.dtype, threeD.size, type(threeD)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

### Import Pandas

In [10]:
import pandas as pd

### Create a DataFrame out of one of the arrays you've created

In [17]:
twoD_df = pd.DataFrame(twoD)
twoD_df

0  1  2
0  1  2  3
1  4  5  6

### Create an array of shape (10, 2) with only ones

In [21]:
ones = np.ones((10, 2), dtype = int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### Create an array of shape (7, 2, 3) of only zeros

In [23]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Create an array within a range of 0 and 100 with step 3

In [24]:
range = np.arange(0, 100, 3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### Create a random array with numbers between 0 and 10 of size (7, 2)

In [33]:
randomI = np.random.randint(0, 10, size = (7, 2))
randomI

array([[5, 1],
       [3, 2],
       [7, 0],
       [7, 6],
       [1, 3],
       [9, 8],
       [1, 5]])

### Create a random array of floats between 0 & 1 of shape (3, 5)

In [32]:
randomF = np.random.rand(3, 5)
randomF

array([[0.15308406, 0.15642384, 0.91633543, 0.52941612, 0.96407373],
       [0.51997152, 0.04770804, 0.38929171, 0.24141845, 0.78846288],
       [0.26187021, 0.99043701, 0.91547527, 0.78431829, 0.38469824]])

### Set the random seed to 42 & Create a random array of numbers between 0 & 10 of size (4, 6)

In [35]:
np.random.seed(42)
randomA = np.random.randint(0, 10, size = (4, 6))
randomA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

### Create an array of random numbers between 1 & 10 of size (3, 7)

In [39]:
randomA2 = np.random.randint(1, 10, size = (3, 7))
randomA2

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

### Find the unique numbers in it

In [38]:
np.unique(randomA2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Find the 0'th index of the latest array you created

In [40]:
randomA2[0]

array([2, 5, 8, 9, 9, 1, 9])

### Get the first 2 rows of latest array you created

In [42]:
randomA2[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

### Get the first 2 values of the first 2 rows of the latest array

In [57]:
randomA2[0:2, 0:2]

array([[2, 5],
       [7, 9]])

### Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5)

In [67]:
randomA3 = np.random.randint(0, 10, size = (3, 5))
ones2 = np.ones((3, 5), dtype = int)
randomA3, ones2

(array([[2, 0, 4, 0, 7],
        [0, 0, 1, 1, 5],
        [6, 4, 0, 0, 2]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

### Add the two arrays together

In [68]:
randomA3 + ones2

array([[3, 1, 5, 1, 8],
       [1, 1, 2, 2, 6],
       [7, 5, 1, 1, 3]])

### Create another array of ones of shape (5, 3)

In [70]:
ones3 = np.ones((5, 3), dtype = int)
ones3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Try add the array of ones and the other most recent array together

In [71]:
randomA3 + ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

##### Why didn't it work? Can you think of a solution?
1. operands could not be broadcast together with shapes (3,5) (5,3)

### Create another array of ones of shape (3, 5)

In [72]:
ones4 = np.ones((3, 5), dtype = int)
ones4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Subtract the new array of ones from the other most recent array

In [73]:
randomA3 - ones4

array([[ 1, -1,  3, -1,  6],
       [-1, -1,  0,  0,  4],
       [ 5,  3, -1, -1,  1]])

### Multiply the ones array with the latest array

In [74]:
randomA3 * ones4

array([[2, 0, 4, 0, 7],
       [0, 0, 1, 1, 5],
       [6, 4, 0, 0, 2]])

### Take the latest array to the power of 2 using '**'

In [75]:
randomA3 ** 2

array([[ 4,  0, 16,  0, 49],
       [ 0,  0,  1,  1, 25],
       [36, 16,  0,  0,  4]], dtype=int32)

### Do the same thing with np.square()

In [76]:
np.square(randomA3)

array([[ 4,  0, 16,  0, 49],
       [ 0,  0,  1,  1, 25],
       [36, 16,  0,  0,  4]], dtype=int32)

### Find the mean of the latest array using np.mean()

In [77]:
np.mean(randomA3)

2.1333333333333333

### Find the maximum of the latest array using np.max()

In [78]:
np.max(randomA3)

7

### Find the minimum of the latest array using np.min()

In [79]:
np.min(randomA3)

0

### Find the standard deviation of the latest array

In [80]:
np.std(randomA3)

2.3626726862225804

### Find the variance of the latest array

In [81]:
np.var(randomA3)

5.5822222222222235

### Reshape the latest array to (3, 5, 1)

In [82]:
np.reshape(randomA3, (3, 5, 1))

array([[[2],
        [0],
        [4],
        [0],
        [7]],

       [[0],
        [0],
        [1],
        [1],
        [5]],

       [[6],
        [4],
        [0],
        [0],
        [2]]])

### Transpose the latest array

In [83]:
np.transpose(randomA3)

array([[2, 0, 6],
       [0, 0, 4],
       [4, 1, 0],
       [0, 1, 0],
       [7, 5, 2]])

### Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)

In [85]:
randomA4 = np.random.randint(0, 10, size = (3, 3))
randomA5 = np.random.randint(0, 10, size = (3, 2))
randomA4, randomA5

(array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8]]),
 array([[5, 2],
        [3, 3],
        [2, 9]]))

### Perform a dot product on the two newest arrays you created

In [86]:
np.dot(randomA4, randomA5)

array([[54, 67],
       [28, 54],
       [41, 82]])

### Create two arrays of random integers between 0 to 10 both of size (4, 3)

In [87]:
randomA6 = np.random.randint(0, 10, size = (4, 3))
randomA7 = np.random.randint(0, 10, size = (4, 3))
randomA6, randomA7

(array([[2, 2, 3],
        [6, 3, 8],
        [0, 7, 6],
        [1, 7, 0]]),
 array([[8, 8, 1],
        [6, 9, 2],
        [6, 9, 8],
        [3, 0, 1]]))

### Perform a dot product on the two newest arrays you created

In [88]:
np.dot(randomA6, randomA7)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

##### Why didn't it work? Can you think of a solution?
1. shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

### Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both

In [110]:
randomA6 = np.transpose(randomA6)
np.dot(randomA6, randomA7)

array([[ 55,  70,  15],
       [ 97, 106,  71],
       [108, 150,  67]])

### Create two arrays of random integers between 0 & 10 of the same shape

In [97]:
randomA8 = np.random.randint(0, 10, size = (3, 3))
randomA9 = np.random.randint(0, 10, size = (3, 3))
randomA8, randomA9

(array([[3, 7, 5],
        [7, 0, 7],
        [3, 0, 7]]),
 array([[3, 5, 7],
        [3, 2, 8],
        [2, 8, 1]]))

### Compare the two arrays with '>'

In [98]:
randomA8 > randomA9

array([[False,  True, False],
       [ True, False, False],
       [ True, False,  True]])

### Compare the two arrays with '>='

In [99]:
randomA8 >= randomA9

array([[ True,  True, False],
       [ True, False, False],
       [ True, False,  True]])

### Find which elements of the first array are greater than 7

In [105]:
randomA8 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### Which parts of each array are equal? (try using '==')

In [101]:
randomA8 == randomA9

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

### Sort one of the arrays you just created in ascending order

In [102]:
np.sort(randomA9)

array([[3, 5, 7],
       [2, 3, 8],
       [1, 2, 8]])

### Sort the indexes of one of the arrays you just created

In [103]:
np.argsort(randomA9)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

### Find the index with the maximum value in one of the arrays you've created

In [104]:
np.argmax(randomA9)

5

### Find the index with the minimum value in one of the arrays you've created

In [106]:
np.argmin(randomA9)

8

### Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created

In [107]:
np.argmax(randomA9, axis = 1)

array([2, 2, 1], dtype=int64)

### Find the indexes with the minimum values across the 0th axis (axis=0) of one of the arrays you created

In [108]:
np.argmin(randomA9, axis = 0)

array([2, 1, 2], dtype=int64)

### Create an array of normally distributed random numbers

In [111]:
array = np.random.randint(0, 100, size = (3, 5, 5))
array

array([[[81, 65, 53, 34, 79],
        [60, 40, 99, 32, 67],
        [32, 13, 20, 47, 19],
        [ 7,  6, 66, 16, 32],
        [47, 75, 58, 85, 21]],

       [[29, 37, 50, 53,  7],
        [26, 26, 97, 20, 29],
        [96, 27, 63, 96, 68],
        [60, 47, 18,  3, 34],
        [63, 48, 16, 43, 91]],

       [[29, 92, 45,  5, 98],
        [36, 23, 92, 45, 52],
        [94, 98, 59, 96, 62],
        [84, 31, 86, 32, 66],
        [17, 24, 94, 53, 57]]])

### Create an array with 10 evenly spaced numbers between 1 and 100

In [112]:
array = np.arange(0, 100, 10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])